eureka:
        instance:
                hostname: localhost
        client:
                registerWithEureka: false
                fetchRegistry: false
                serviceUrl:
                        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
                        #自己作为服务器，公布出来的地址。 比如后续某个微服务要把自己注册到 eureka server,
                        #那么就要使用这个地址： http://localhost:8761/eureka/

spring:
        application:
                name: eureka-server
                #表示这个微服务本身的名称是 eureka-server

