#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: product-view-service-feign
#  for 链路追踪
  zipkin:
    base-url: http://localhost:9411

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
#    content-type: text/html

